services:
  api:
    build:
      context: ./CryptoExchange      # Путь к Dockerfile
    ports:
      - "8080:8080"                  # Проброс порта
    volumes:
      - ./CryptoExchange/config.json:/app/config.json   # монтируем папку для просмотра внутри контейнера
    stdin_open: true
    tty: true                         # Для работы с терминалом внутри контейнера
    depends_on:
      - db                           # Сначала запускается база данных
    restart: always

  db:
    build:
      context: ./DataBaseDAS               # Путь к Dockerfile вашей базы данных
    ports:
      - "7432:7432"                     # Проброс порта TCP сервера
    volumes:
      - ./DataBaseDAS/exchange:/app/exchange # Том для хранения данных
      - ./DataBaseDAS/schema.json:/app/schema.json
    restart: always                  # Перезапуск при сбое